import os
import asyncio
from typing import AsyncGenerator

def generate_env_file(state, filepath: str = ".env") -> None:
    """
    Generates the .env file for docker-compose based on the App state.
    """
    env_content = (
        f"# Auto-generated by smart-db Setup Wizard\n"
        f"LLM_MODEL={state.model_name}\n"
        f"LLM_BACKEND={state.backend}\n"
        f"GPU_TIER={state.assigned_tier}\n"
    )
    with open(filepath, "w") as f:
        f.write(env_content)

async def run_docker_compose_up(cwd: str = ".") -> AsyncGenerator[str, None]:
    """
    Runs docker-compose up -d --build and yields combined stdout/stderr lines.
    2>&1 redirects stderr to stdout so we can stream it all sequentially.
    """
    process = await asyncio.create_subprocess_shell(
        "docker compose up -d --build 2>&1",
        stdout=asyncio.subprocess.PIPE,
        cwd=cwd
    )

    if process.stdout:
        while True:
            line = await process.stdout.readline()
            if not line:
                break
            yield line.decode().rstrip()
            
    await process.wait()
    
    if process.returncode != 0:
        raise RuntimeError(f"docker compose failed with exit code {process.returncode}")
